### PR TITLE
Fix problems reported by PHPStan

### PR DESCRIPTION
**Pull request by szepeviktor**
Some remarks.

- loose comparision is no one's friend
- move types from PHPDoc to typehints
- put errors in conditionals, leave expected operations without indentation

### CODE REVIEW

**Comment by szepeviktor** [comment]
> put errors in conditionals, leave expected operations without indentation

```php
        if (get_option('show_on_front') == 'page') {
            $static_page_id = (int) get_option('page_on_front');
            return $static_page_id > 0 ? $static_page_id : null;
        }

        return null;

// becomes

        if (get_option('show_on_front') !== 'page') {
            // Errors go in here
            return null;
        }

        // This is the expected operation
        $static_page_id = (int) get_option('page_on_front');
        return $static_page_id > 0 ? $static_page_id : null;
```

**Comment by leoloso** [comment]
Ok, will fix it now

**Comment by leoloso** [comment]
Btw, I've added your dependency to all WordPress components. Do you want to run phpstan for all of them? The list of components is this one:

- https://github.com/getpop/api-endpoints-for-wp.git
- https://github.com/PoPSchema/commentmeta-wp.git
- https://github.com/PoPSchema/comments-wp.git
- https://github.com/PoPSchema/custompostmedia-wp.git
- https://github.com/PoPSchema/custompostmeta-wp.git
- https://github.com/PoPSchema/customposts-wp.git
- https://github.com/getpop/engine-wp.git
- https://github.com/GraphQLByPoP/graphql-clients-for-wp.git
- https://github.com/GraphQLByPoP/graphql-endpoint-for-wp.git
- https://github.com/getpop/hooks-wp.git
- https://github.com/PoPSchema/media-wp.git
- https://github.com/getpop/metaquery-wp.git
- https://github.com/PoPSchema/pages-wp.git
- https://github.com/PoPSchema/post-tags-wp.git
- https://github.com/PoPSchema/posts-wp.git
- https://github.com/getpop/queriedobject-wp.git
- https://github.com/getpop/routing-wp.git
- https://github.com/PoPSchema/tags-wp.git
- https://github.com/PoPSchema/taxonomies-wp.git
- https://github.com/PoPSchema/taxonomymeta-wp.git
- https://github.com/PoPSchema/taxonomyquery-wp.git
- https://github.com/getpop/translation-wp.git
- https://github.com/getpop/user-roles-wp.git
- https://github.com/getpop/user-state-wp.git
- https://github.com/PoPSchema/usermeta-wp.git
- https://github.com/PoPSchema/users-wp.git

Btw2: just to let you know, I've just upgraded the minimum PHP for `graphql-api` to 7.2.5, I was unaware that a dependency requires that. 

Btw3: I'm almost done setting-up Travis CI

**Comment by szepeviktor** [comment]
> Do you want to run phpstan for all of them?

Yes, providing you pay me for revitalizing your code and maintaining your repos.

**Comment by szepeviktor** [comment]
> getpop/hooks-wp.git

This is my Fantasy Trio of OOP hooking: https://github.com/szepeviktor/Toolkit4WP/tree/master/src (`Hook*.php`)

**Comment by leoloso** [comment]
I wish I could :) 

Sorry for asking you to do things. It was not my intention to make you work. But, tbh, If I can make money from `graphql-api` I could consider it ;) It's too soon to tell right now

**Comment by leoloso** [comment]
> This is my Fantasy Trio of OOP hooking: https://github.com/szepeviktor/Toolkit4WP/tree/master/src (`Hook*.php`)

I'm open to suggestions, if they improve `graphql-api`. Be welcome make propositions, through new issues

**Comment by szepeviktor** [comment]
> I'm open to suggestions, if they improve `graphql-api`.

I'm entering code into my computer in theory only!

**Comment by leoloso** [comment]
I'm checking the list. A project in your `README` doesn't exist: https://github.com/inpsyde/wp-events

**Comment by szepeviktor** [comment]
> A project in your `README` doesn't exist: [inpsyde/wp-events](https://github.com/inpsyde/wp-events)

Yes, it a private repo. Ask inpsyde people when they open it up!

**Pull request merged**
